# Usa a imagem oficial do Python como base
FROM python:3.10-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /CollatzMath

# Copia o arquivo de dependências para o contêiner
COPY CollatzConjecture.py .

# Comando para rodar o seu script Python quando o container iniciar
CMD ["python", "CollatzConjecture.py"]
